#DNS Check Configuration
#Please replace the values below based on the DNS name you want check
dnsname: github.com #This is the name we are going to be checking
correctip: ["192.30.252.131", "192.30.252.129", "192.30.252.128"] #This is the IP or IPs what we are going to be comparing against
nameserver: 8.8.8.8 #This is the default nameserver, Google DNS, you can specify your own

#Notification configuration
#Please set the values for the notification functionality of DNS Checker
smtpserver: smtp.domain.com #this is an smtp server in your enviroment where emails can be sent
recipients: youremail@domain.com, someoneelse@domain.com #the indended recipients seperated by a comma
fromaddress: ruby@yourdomain.com #This is the from address you would like your message to come from
